data: 
  channels: 3
  dataset: CIFAR10
  horizontal_flip: true
  image_size: 32
  lambda_logit: 0.05
model: 
  act_norm: false
  batch_norm: false
  latent_size: 85
  n_iters: 10
  n_layers: 16
  n_subsampling: 2
  rgb_last: true
  zero_init_start: 12
optim: 
  adam_eps: 0.0001
  amsgrad: true
  beta1: 0.9
  lr: 0.001
  optimizer: Adam
  weight_decay: 0
training:
  ema: false
  batch_size: 32
  log_interval: 10
  n_epochs: 100
  snapshot_interval: 10
