training:
  n_epochs: 500
  batch_size: 64
  log_interval: 10

data:
#  dataset: MNIST
#  image_size: 28
#  channels: 1
#  num_classes: 10
  
  dataset: CIFAR10
  image_size: 32
  channels: 3
  num_classes: 10

model:
  n_layers: 24
  latent_size: 32
  n_subsampling: 2


optim:
  optimizer: Adam
  lr: 0.001
  beta1: 0.9
  weight_decay: 0.000001
  amsgrad: True
