training:
  n_epochs: 500
  batch_size: 64
  log_interval: 10

data:
  dataset: MNIST
  image_size: 28
  channels: 1
  num_classes: 10
  
#  dataset: CIFAR10
#  image_size: 32
#  lambda_logit: 0.05

model:
  layer_size:
    - 2
    - 2
    - 1
    - 1
  latent_size:
    - 16
    - 8
    - 4
    - 1

optim:
  optimizer: Adam
  lr: 0.01
  beta1: 0.9
  weight_decay: 0.000001
