training:
  n_epochs: 500
  batch_size: 64
  log_interval: 10
  snapshot_interval: 10

data:
  #  dataset: MNIST
  #  image_size: 28
  #  channels: 1
  #  num_classes: 10
  dataset: CIFAR10
  image_size: 32
  channels: 3
  num_classes: 10
  augmentation: true

model:
  n_layers: 19
  latent_size: 16
  n_subsampling: 2
  act_norm: false

optim:
  optimizer: Adam
  lr: 0.0001
  beta1: 0.9
  weight_decay: 0.000001
  amsgrad: true
#  eps: 0.00000001
  eps: 0.0001
