training:
  #  n_epochs: 200 # cifar-10
  n_epochs: 200 # imagenet
  maximum_steps: 350000 # imagenet
  batch_size: 64
  log_interval: 10
#  snapshot_interval: 10 # cifar-10
  snapshot_interval: 10 

data:
  dataset: bsds300 #7*3 space2depth
  image_size: 63
  channels: 1

#  dataset: gas
#  image_size: 8
#  channels: 1

#  dataset: hepmass
#  image_size: 21
#  channels: 1

#  dataset: miniboone
#  image_size: 43
#  channels: 1

#  dataset: power
#  image_size: 6
#  channels: 1


model:
  n_layers: 5
  latent_size: 200 #100 #210
  n_subsampling: 1
  act_norm: false
  rgb_last: true
  batch_norm: false
  zero_init_start: 100

  # for sampling
  n_iters: 200

optim:
  optimizer: Adam
  lr: 0.001
  beta1: 0.9
  weight_decay: 0
  amsgrad: true
  adam_eps: 0.0001

analysis:
  newton_iter: 1000

